version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/riko-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      # - dbCL
      # - dbFR
    
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  
  celery:
    build: .
    command: celery -A api worker -l info
    volumes:
      - .:/riko-backend
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  
  celery-beat:
    build: .
    command: celery -A api worker -l info
    volumes:
      - .:/riko-backend
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=riko
    ports:
      - "5432"

  # dbCL:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data_CL:/var/lib/postgresql/CL
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=rikoCL
  #   ports:
  #     - "5434:5432"

  # dbFR:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data_FR:/var/lib/postgresql/FR
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=rikoFR
  #   ports:
  #     - "5435:5432"

volumes:
  postgres_data:
  # postgres_data_CL:
  # postgres_data_FR: