# Generated by Django 3.0.8 on 2020-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
