# Generated by Django 3.0.8 on 2020-12-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201208_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
