# Generated by Django 3.0.8 on 2020-12-13 23:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_isdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closedDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default=[], max_length=13),
        ),
    ]
