# Generated by Django 3.0.8 on 2021-01-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mydevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chargeId',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
