# Generated by Django 3.0.8 on 2021-01-13 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210113_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completedOrderDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lastPayment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
