# Generated by Django 3.0.8 on 2021-01-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210113_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='todayDish',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todayDish', to='api.Dish'),
        ),
    ]
