# Generated by Django 3.0.8 on 2021-01-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurant_todaydish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='todayDish',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todayDish', to='api.Dish'),
        ),
    ]
