# Generated by Django 3.0.8 on 2021-01-20 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210120_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='api/uploads/claims/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
