XXXXXXXXX XXXXX
BBBB BBBBBB
BBBB BBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXX

XXXX XXXXX XXXXXX XXXX XXX
XXXXXXX XXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXX
				XX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXX XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXXXXXXX
					XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXXXXXXX
					XXXXXX XXXXXBBB BBBBBBBX gettext(u'I want to be a chef!') XXXXXXXXX
				XXXXX
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXXXXX
XXXX XXX XXXXXX XXXX XXX