XXXXXXXXX XXXXX
BBBB BBBBBB
BBBB BBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXX

XXXXXX
	XXXX XXXXXX XXXXXXXX XXXX XXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXX
	XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXX XXXXXX XXXX XXX
	XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
	XXXX XXXX XXXXXXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
	XXXX XXXX XXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
	XXXX XXXX XXXXXXXXX XXX XXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXX XXXX XXXXX XXX
	XXXXXXX gettext(u'Riko - Great food, Great prices') XXXXXXXX

	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXX
			XXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
XXXXXXX